services:
    test_app:
        build:
            context: .
            dockerfile: Dockerfile.test
        container_name: test_app
        command: tail -f /dev/null
        volumes:
            - ./src:/usr/src/app/src:cached
            - ./tests:/usr/src/app/tests:cached
            - ./pytest.ini:/usr/src/app/pytest.ini:cached
        depends_on:
            - test_db
        env_file:
            - .env.test
        networks:
            - test_network

    test_db:
        image: postgres:14
        container_name: test_db
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test
        volumes:
            - testdata:/var/lib/postgresql/data/
        ports:
            - "2345:5432"
        networks:
            - test_network

networks:
    test_network:

volumes:
    testdata:
