"""test

Revision ID: 1e5982fabd74
Revises: ad2173534e52
Create Date: 2025-05-05 18:33:45.638687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e5982fabd74'
down_revision: Union[str, None] = 'ad2173534e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chore_completion', sa.Column('family_id', sa.UUID(), nullable=False))
    op.alter_column('chore_completion', 'chore_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('chore_completion', 'completed_by_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'chore_completion', 'family', ['family_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.drop_column('users', 'hashed_password')
    op.add_column('users_family_permissions', sa.Column('can_invite_users', sa.Boolean(), nullable=False))
    op.add_column('users_settings', sa.Column('language', sa.String(), nullable=False))
    op.add_column('users_settings', sa.Column('date_of_birth', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_settings', 'date_of_birth')
    op.drop_column('users_settings', 'language')
    op.drop_column('users_family_permissions', 'can_invite_users')
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'password')
    op.drop_constraint(None, 'chore_completion', type_='foreignkey')
    op.alter_column('chore_completion', 'completed_by_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('chore_completion', 'chore_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('chore_completion', 'family_id')
    # ### end Alembic commands ###
