"""init_test_2

Revision ID: ad2173534e52
Revises: 407dbbad7552
Create Date: 2025-04-14 14:53:33.424641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad2173534e52'
down_revision: Union[str, None] = '407dbbad7552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'family', 'users', ['family_admin_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'family', type_='foreignkey')
    # ### end Alembic commands ###
