"""comment

Revision ID: 045b77d6d5c7
Revises: 271324a90232
Create Date: 2025-02-25 18:12:12.314770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '045b77d6d5c7'
down_revision: Union[str, None] = '271324a90232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('family_settings')
    op.add_column('chores', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('chores', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'chores', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('family', sa.Column('icon', sa.String(), nullable=False))
    op.add_column('family', sa.Column('family_admin_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'family', 'users', ['family_admin_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'is_family_admin')
    op.drop_column('users_family_permissions', 'can_promote_user')
    op.drop_column('users_family_permissions', 'should_confirm_creating_chore')
    op.drop_column('users_family_permissions', 'can_invite_users')
    op.drop_column('users_family_permissions', 'can_create_chore')
    op.drop_column('users_family_permissions', 'can_change_family_name')
    op.drop_column('users_family_permissions', 'can_kick_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_family_permissions', sa.Column('can_kick_user', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users_family_permissions', sa.Column('can_change_family_name', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users_family_permissions', sa.Column('can_create_chore', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users_family_permissions', sa.Column('can_invite_users', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users_family_permissions', sa.Column('should_confirm_creating_chore', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users_family_permissions', sa.Column('can_promote_user', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_family_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'family', type_='foreignkey')
    op.drop_column('family', 'family_admin_id')
    op.drop_column('family', 'icon')
    op.drop_constraint(None, 'chores', type_='foreignkey')
    op.drop_column('chores', 'created_by')
    op.drop_column('chores', 'is_active')
    op.create_table('family_settings',
    sa.Column('family_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('confirm_by_all_admins', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('icon', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], name='family_settings_family_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='family_settings_pkey')
    )
    # ### end Alembic commands ###
