"""update user password field

Revision ID: 09910561ae1a
Revises: 35462464481e
Create Date: 2025-05-02 20:01:10.518001

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '09910561ae1a'
down_revision: Union[str, None] = '35462464481e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password', new_column_name='password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password', new_column_name='hashed_password')
    # ### end Alembic commands ###
