"""remove column buyer_id from Profuct

Revision ID: 1352cad453c7
Revises: a13f6a60c1e5
Create Date: 2025-03-10 08:47:14.944530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1352cad453c7'
down_revision: Union[str, None] = 'a13f6a60c1e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_buyer_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'buyer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('buyer_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('products_buyer_id_fkey', 'products', 'users', ['buyer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
