"""comment

Revision ID: 567a9bed8181
Revises: 6d45c510033e
Create Date: 2025-05-02 19:11:22.063894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '567a9bed8181'
down_revision: Union[str, None] = '6d45c510033e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_family_permissions', sa.Column('can_invite_users', sa.Boolean(), nullable=True))
    op.execute("""
        UPDATE users_family_permissions
        SET can_invite_users = true
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_family_permissions', 'can_invite_users')
    # ### end Alembic commands ###
