"""add one to one field

Revision ID: 625e15194853
Revises: c9a57e7bb9e3
Create Date: 2025-03-27 12:57:06.998227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '625e15194853'
down_revision: Union[str, None] = 'c9a57e7bb9e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users_family_permissions', ['user_id'])
    op.create_unique_constraint(None, 'users_settings', ['user_id'])
    op.create_unique_constraint(None, 'wallets', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallets', type_='unique')
    op.drop_constraint(None, 'users_settings', type_='unique')
    op.drop_constraint(None, 'users_family_permissions', type_='unique')
    # ### end Alembic commands ###
