"""comment

Revision ID: 6d45c510033e
Revises: e7ac08ed8a8e
Create Date: 2025-05-02 19:08:17.611591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d45c510033e'
down_revision: Union[str, None] = 'e7ac08ed8a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chore_completion', 'chore_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('chore_completion', 'completed_by_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('chore_completion_family_id_fkey', 'chore_completion', type_='foreignkey')
    op.create_foreign_key(None, 'chore_completion', 'family', ['family_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chore_completion', type_='foreignkey')
    op.create_foreign_key('chore_completion_family_id_fkey', 'chore_completion', 'family', ['family_id'], ['id'], ondelete='SET NULL')
    op.alter_column('chore_completion', 'completed_by_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('chore_completion', 'chore_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
