"""delete field synced_to_ch

Revision ID: 981b397817ed
Revises: a5c40972790b
Create Date: 2025-04-26 05:51:28.330616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '981b397817ed'
down_revision: Union[str, None] = 'a5c40972790b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chore_completion', 'synced_to_ch')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chore_completion', sa.Column('synced_to_ch', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
