"""create new transaction models

Revision ID: a13f6a60c1e5
Revises: bc815b6dcef1
Create Date: 2025-03-02 01:07:19.295589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a13f6a60c1e5'
down_revision: Union[str, None] = 'bc815b6dcef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peer_transactions',
    sa.Column('transaction_type', sa.Enum('transfer', 'purchase', name='peer_transaction', native_enum=False), nullable=False),
    sa.Column('from_user_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('detail', sa.String(), nullable=False),
    sa.Column('coins', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('to_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peer_transactions_from_user_id'), 'peer_transactions', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_peer_transactions_product_id'), 'peer_transactions', ['product_id'], unique=False)
    op.create_index(op.f('ix_peer_transactions_to_user_id'), 'peer_transactions', ['to_user_id'], unique=False)
    op.create_table('product_buyers',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reward_transactions',
    sa.Column('transaction_type', sa.Enum('reward_for_chore', name='system_transaction', native_enum=False), nullable=False),
    sa.Column('chore_completion_id', sa.UUID(), nullable=True),
    sa.Column('detail', sa.String(), nullable=False),
    sa.Column('coins', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('to_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['chore_completion_id'], ['chore_completion.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_transactions_chore_completion_id'), 'reward_transactions', ['chore_completion_id'], unique=False)
    op.create_index(op.f('ix_reward_transactions_to_user_id'), 'reward_transactions', ['to_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reward_transactions_to_user_id'), table_name='reward_transactions')
    op.drop_index(op.f('ix_reward_transactions_chore_completion_id'), table_name='reward_transactions')
    op.drop_table('reward_transactions')
    op.drop_table('product_buyers')
    op.drop_index(op.f('ix_peer_transactions_to_user_id'), table_name='peer_transactions')
    op.drop_index(op.f('ix_peer_transactions_product_id'), table_name='peer_transactions')
    op.drop_index(op.f('ix_peer_transactions_from_user_id'), table_name='peer_transactions')
    op.drop_table('peer_transactions')
    # ### end Alembic commands ###
