"""change field synced_to_ch

Revision ID: a5c40972790b
Revises: fb07dbde8524
Create Date: 2025-04-22 19:19:53.615247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c40972790b'
down_revision: Union[str, None] = 'fb07dbde8524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE chore_completion SET synced_to_ch = False WHERE synced_to_ch IS NULL")
    op.alter_column('chore_completion', 'synced_to_ch',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chore_completion', 'synced_to_ch',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
