"""delete_wallet_transaction

Revision ID: c9a57e7bb9e3
Revises: 1352cad453c7
Create Date: 2025-03-13 08:20:15.792658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9a57e7bb9e3'
down_revision: Union[str, None] = '1352cad453c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallets_transactions')
    op.alter_column('chore_completion', 'chore_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('chore_completion', 'completed_by_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chore_completion', 'completed_by_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('chore_completion', 'chore_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_table('wallets_transactions',
    sa.Column('transaction_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('coins', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('from_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('to_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('chore_completion_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chore_completion_id'], ['chore_completion.id'], name='wallets_transactions_chore_completion_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name='wallets_transactions_from_user_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='wallets_transactions_product_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], name='wallets_transactions_to_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='wallets_transactions_pkey')
    )
    # ### end Alembic commands ###
