"""add family_id to chore_completion

Revision ID: e7ac08ed8a8e
Revises: 981b397817ed
Create Date: 2025-04-26 06:00:03.020813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7ac08ed8a8e'
down_revision: Union[str, None] = '981b397817ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chore_completion', sa.Column('family_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'chore_completion', 'family', ['family_id'], ['id'], ondelete='SET NULL')
    op.execute("""
        UPDATE chore_completion cc
        SET family_id = chores.family_id
        FROM chores
        WHERE cc.chore_id = chores.id
    """)
    op.alter_column('chore_completion', 'family_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chore_completion', type_='foreignkey')
    op.drop_column('chore_completion', 'family_id')
    # ### end Alembic commands ###
